server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigw
  cloud:
    gateway:
      routes:
        - id: greeting-phrase-api
          uri: lb://greeting-phrase-api
          predicates:
            - Path=/greetingword/**

        - id: guest-person-api
          uri: lb://guest-person-api
          predicates:
            - Path=/guestperson/**

        - id: greeting-service
          uri: lb://greeting-service
          predicates:
            - Path=/greeting-full/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG