server:
  port: 8082

spring:
  application:
    name: guest-person-api

  sleuth:
    sampler:
      probability: 1.0

    zipkin:
      base-url: http://localhost:9411
      enabled: true

  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.micfro.guestpersonapi: DEBUG
