server:
  port: 8080

spring:
  application:
    name: greeting-service

  sleuth:
    sampler:
      probability:

    zipkin:
      base-url: http://localhost:9411
      enabled: true

management:
  tracing:
    enabled: true
    sampling:
       probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.example.greeting: DEBUG

