server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigw

  sleuth:
    sampler:
      probability: 1.0

    zipkin:
      base-url: http://localhost:9411
      enabled: true

  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0

  cloud:
    gateway:
      routes:
        - id: greeting-phrase-api
          uri: lb://greeting-phrase-api
          predicates:
            - Path=/greetingword/**

        - id: guest-person-api
          uri: lb://guest-person-api
          predicates:
            - Path=/guestperson/**

        - id: greeting-service
          uri: lb://greeting-service
          predicates:
            - Path=/greeting-full/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG